create Conduit Container
JohnTwiiX/Conduit_Container pull request #1
Opened 2024-09-02 12:53 UTC by JohnTwiiX

# Description
add docker compose, readme file, fe and be repo

2024-09-04 19:39 UTC, spmse requested changes

2024-09-04 19:39 UTC, spmse commented on README.md
> +A Docker Compose container that builds two containers, a Conduit backend and a Conduit frontend.
```suggestion
A Docker Compose definition that contains two containerized services, a django backend and a  angular frontend for the conduit application - a medium.com clone created to showcase API-Specification definitions and how to develop a more complex system in different Technology-Stacks.
```

2024-09-04 19:39 UTC, spmse commented on README.md
> +- Docker Compose
missing requirements:

- Docker
- Basic Knowledge about container definition
- basic knowledge about shell-scripting, python, and linux

2024-09-04 19:39 UTC, spmse commented on README.md
> +1. start the conatiner
typo:
```suggestion
1. start the container
```

2024-09-04 19:39 UTC, spmse commented on README.md
> +1. start the conatiner
Would rather say: "Navigate to repo" followed by the `cd` command (maybe even inline -> same line). Then in the next line you can do something like start the container with "docker compose up -d", with the info that `-d` stands for detached mode and a litte explanation what this exactly means

2024-09-04 19:39 UTC, spmse commented on README.md
> +- the conduit-frontend is on port 8282
In order to make this fit into the course curricullum, I would propose the following ports:

- FE: 8084
- BE: 8085

2024-09-04 19:39 UTC, spmse commented on docker-compose.yaml
> +    command: gunicorn --workers 3 --bind 0.0.0.0:8000 conduit.wsgi:application
This is only necessary because you used `CMD` instead of `ENTRYPOINT` keyword in your corresponding Dockerfile, so there is not entrypoint for the container.

As an additional docs-task for you, i'd like to have an explanation what's the difference between using ENTRYPOINT and CMD --> they might be valid solutions as last Instruction for a containersfile, but might also bring some caveats that you surely want to avoid when knowing them.

2024-09-04 19:39 UTC, spmse commented on docker-compose.yaml
> +
what about the network definition? I want to read something about that in the README for sure, because otherwise i am not quite sure if you understood container-to-container communication.

You're right with the statement "there is the default network", but think one step further: what does this mean? What could happen when not providing a network definition explicitly? 

What would have to change from a security perspective if I would task you to create one big compose file that defines all of your services for the V-Server?
What could be potential risks for your V-Server/Applications? 

==> Add to README, please

2024-09-05 07:29 UTC, JohnTwiiX commented on docker-compose.yaml
> +    command: gunicorn --workers 3 --bind 0.0.0.0:8000 conduit.wsgi:application
cmd können beim erstellen der Container verändert werden

2024-09-05 07:30 UTC, JohnTwiiX commented on docker-compose.yaml
> +
Ich hatte gesagt, dass ich dachte, dass die Kommunikation zwischen FE und BE nur über das Docker Netzwerk funktionieren soll.. ich aber das Docker Netzwerk wieder rausgenommen hab und deshalb das nicht mit einbinde

2024-09-13 07:58 UTC, spmse approved these changes
Hi John, I missed to save the comments (again) - sorry! But this is rather an improvement and no blocker for your submission. So feel free to adjust these things if you want and to prevent other problems

2024-09-13 07:58 UTC, spmse commented on .gitignore
> +.env
```console
**/*.env.*
!.env.example
```

2024-09-13 07:58 UTC, spmse commented on README.md
> +   git checkout <branch-name>
better use `switch` to prevent disambiguities or user-land errors when changing branches.

2024-09-13 11:55 UTC, merged